name: First pipeline
on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: cp .env.ci .env
      - name: Install Dependencies
        run: composer install -q !$no-ansi !$no-interaction !$no-scripts !$no-progress
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: phpstan
        run: ./vendor/bin/phpstan analyse !$memory-limit=1G
